'use strict';

module.exports = {
  AUTH: {
    USERNAME_OR_PASSWORD_IS_INCORRECT: 'USERNAME_OR_PASSWORD_IS_INCORRECT',
    EMAIL_IS_NOT_CONFIRMED: 'EMAIL_IS_NOT_CONFIRMED',
    EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
    PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
    TOKEN_IS_INCORRECT: 'TOKEN_IS_INCORRECT',
  }
};
